import { GameMode } from './types';
export declare const APP_TITLE = "TOSIOS";
export declare const WS_PORT = 3001;
export declare const ROOM_NAME = "game";
export declare const ROOM_REFRESH = 3000;
export declare const PLAYERS_REFRESH = 1000;
export declare const DEBUG = false;
export declare const MAPS_NAMES: string[];
export declare const ROOM_PLAYERS_MIN = 2;
export declare const ROOM_PLAYERS_MAX = 16;
export declare const ROOM_PLAYERS_SCALES: number[];
export declare const ROOM_NAME_MAX = 16;
export declare const PLAYER_NAME_MAX = 16;
export declare const LOG_LINES_MAX = 5;
export declare const LOBBY_DURATION: number;
export declare const GAME_DURATION: number;
export declare const GAME_MODES: GameMode[];
export declare const BACKGROUND_COLOR = "#25131A";
export declare const TILE_SIZE = 32;
export declare const PLAYER_SIZE = 32;
export declare const PLAYER_SPEED = 1;
export declare const PLAYER_MAX_LIVES = 3;
export declare const PLAYER_WEAPON_SIZE = 12;
export declare const PLAYER_HEARING_DISTANCE = 256;
export declare const MONSTERS_COUNT = 3;
export declare const MONSTER_SIZE = 32;
export declare const MONSTER_SPEED_PATROL = 0.75;
export declare const MONSTER_SPEED_CHASE = 1.25;
export declare const MONSTER_SIGHT = 192;
export declare const MONSTER_LIVES = 3;
export declare const MONSTER_IDLE_DURATION_MIN = 1000;
export declare const MONSTER_IDLE_DURATION_MAX = 3000;
export declare const MONSTER_PATROL_DURATION_MIN = 1000;
export declare const MONSTER_PATROL_DURATION_MAX = 3000;
export declare const MONSTER_ATTACK_BACKOFF = 3000;
export declare const FLASKS_COUNT = 3;
export declare const FLASK_SIZE = 24;
export declare const BULLET_SIZE = 8;
export declare const BULLET_SPEED = 4;
export declare const BULLET_RATE = 800;
