"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MENU = exports.LEADERBOARD = exports.SHOOT = exports.RIGHT = exports.LEFT = exports.DOWN = exports.UP = void 0;
exports.UP = ['KeyW', 'KeyZ', 'ArrowUp'];
exports.DOWN = ['KeyS', 'ArrowDown'];
exports.LEFT = ['KeyA', 'KeyQ', 'ArrowLeft'];
exports.RIGHT = ['KeyD', 'ArrowRight'];
exports.SHOOT = ['Space'];
exports.LEADERBOARD = ['Tab'];
exports.MENU = ['Escape'];
